[[language]]
name = "python"
# Make sure to include both servers in the list
language-servers = [ "basedpyright", "ruff" ]

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.basedpyright.config]
basedpyright.analysis.diagnosticMode = "openFilesOnly"

# Use the ruff-lsp configuration
[language-server.ruff] 
command = "ruff-lsp"
[language-server.ruff.config.settings]
args = ["--ignore", "E501"]
