[[language]]
name = "python"
# Make sure to include both servers in the list
language-servers = [ "basedpyright", "ruff" ]

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.basedpyright.config]
basedpyright.analysis.diagnosticMode = "openFilesOnly"

# Use the ruff-lsp configuration
[language-server.ruff] 
command = "ruff-lsp"
[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[[language]]
name = "toml"
# https://github.com/tamasfe/taplo/issues/580#issuecomment-2004174721
roots = ["."]
language-servers = ["taplo"]

[[language]]
name = "rust"
language-servers = ["rust-analyze"]
[language-server.rust-analyzer.config.check]
command = "clippy"
